version: '3'
services:
  mysql:
    image: joao159159/mysql-pers:latest
    restart: always
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: 159159
      MYSQL_ROOT_PASSWORD: 159159
      SERVICE_NAME: mysql
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql-data: